// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vconnect.h for the primary calling header

#ifndef VERILATED_VCONNECT___024ROOT_H_
#define VERILATED_VCONNECT___024ROOT_H_  // guard

#include "verilated.h"


class Vconnect__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vconnect___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst,0,0);
        VL_IN8(start,0,0);
        VL_OUT8(done,0,0);
        CData/*0:0*/ connect__DOT__quant_y_done;
        CData/*0:0*/ connect__DOT__quant_cb_done;
        CData/*0:0*/ connect__DOT__quant_cr_done;
        CData/*1:0*/ connect__DOT__rgb2ycbcr_inst__DOT__state;
        CData/*1:0*/ connect__DOT__rgb2ycbcr_inst__DOT__next_state;
        CData/*2:0*/ connect__DOT__rgb2ycbcr_inst__DOT__batch_count;
        CData/*0:0*/ connect__DOT__rgb2ycbcr_inst__DOT__done_reg;
        CData/*2:0*/ connect__DOT__dct_y__DOT__state;
        CData/*2:0*/ connect__DOT__dct_y__DOT__nstate;
        CData/*2:0*/ connect__DOT__dct_y__DOT__row_cnt;
        CData/*2:0*/ connect__DOT__dct_y__DOT__col_cnt;
        CData/*0:0*/ connect__DOT__dct_y__DOT__we_trans;
        CData/*0:0*/ connect__DOT__dct_y__DOT__core_in_valid;
        CData/*2:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__state;
        CData/*2:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__nstate;
        CData/*2:0*/ connect__DOT__dct_cb__DOT__state;
        CData/*2:0*/ connect__DOT__dct_cb__DOT__nstate;
        CData/*2:0*/ connect__DOT__dct_cb__DOT__row_cnt;
        CData/*2:0*/ connect__DOT__dct_cb__DOT__col_cnt;
        CData/*0:0*/ connect__DOT__dct_cb__DOT__we_trans;
        CData/*0:0*/ connect__DOT__dct_cb__DOT__core_in_valid;
        CData/*2:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__state;
        CData/*2:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__nstate;
        CData/*2:0*/ connect__DOT__dct_cr__DOT__state;
        CData/*2:0*/ connect__DOT__dct_cr__DOT__nstate;
        CData/*2:0*/ connect__DOT__dct_cr__DOT__row_cnt;
        CData/*2:0*/ connect__DOT__dct_cr__DOT__col_cnt;
        CData/*0:0*/ connect__DOT__dct_cr__DOT__we_trans;
        CData/*0:0*/ connect__DOT__dct_cr__DOT__core_in_valid;
        CData/*2:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__state;
        CData/*2:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__nstate;
        CData/*1:0*/ connect__DOT__quant_y__DOT__state;
        CData/*1:0*/ connect__DOT__quant_y__DOT__next_state;
        CData/*2:0*/ connect__DOT__quant_y__DOT__cycle_cnt;
        CData/*5:0*/ connect__DOT__quant_y__DOT__addr;
        CData/*1:0*/ connect__DOT__quant_cb__DOT__state;
        CData/*1:0*/ connect__DOT__quant_cb__DOT__next_state;
        CData/*2:0*/ connect__DOT__quant_cb__DOT__cycle_cnt;
        CData/*5:0*/ connect__DOT__quant_cb__DOT__addr;
        CData/*1:0*/ connect__DOT__quant_cr__DOT__state;
        CData/*1:0*/ connect__DOT__quant_cr__DOT__next_state;
        CData/*2:0*/ connect__DOT__quant_cr__DOT__cycle_cnt;
        CData/*5:0*/ connect__DOT__quant_cr__DOT__addr;
        CData/*2:0*/ __Vdly__connect__DOT__rgb2ycbcr_inst__DOT__batch_count;
        CData/*2:0*/ __Vdly__connect__DOT__dct_y__DOT__row_cnt;
        CData/*2:0*/ __Vdly__connect__DOT__dct_y__DOT__col_cnt;
        CData/*2:0*/ __Vdly__connect__DOT__dct_cb__DOT__row_cnt;
        CData/*2:0*/ __Vdly__connect__DOT__dct_cb__DOT__col_cnt;
        CData/*2:0*/ __Vdly__connect__DOT__dct_cr__DOT__row_cnt;
        CData/*2:0*/ __Vdly__connect__DOT__dct_cr__DOT__col_cnt;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst__0;
        CData/*0:0*/ __VactContinue;
        VL_INW(r_all,511,0,16);
        VL_INW(g_all,511,0,16);
        VL_INW(b_all,511,0,16);
        VL_OUTW(y_quantized,1023,0,32);
        VL_OUTW(cb_quantized,1023,0,32);
    };
    struct {
        VL_OUTW(cr_quantized,1023,0,32);
        VlWide<64>/*2047:0*/ connect__DOT__dct_y_out;
        VlWide<64>/*2047:0*/ connect__DOT__dct_cb_out;
        VlWide<64>/*2047:0*/ connect__DOT__dct_cr_out;
        IData/*31:0*/ connect__DOT__rgb2ycbcr_inst__DOT__k;
        IData/*31:0*/ connect__DOT__rgb2ycbcr_inst__DOT__j;
        VlWide<64>/*2047:0*/ connect__DOT__rgb2ycbcr_inst__DOT__y_reg;
        VlWide<64>/*2047:0*/ connect__DOT__rgb2ycbcr_inst__DOT__cb_reg;
        VlWide<64>/*2047:0*/ connect__DOT__rgb2ycbcr_inst__DOT__cr_reg;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__0__KET____DOT__converter__DOT__y_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__0__KET____DOT__converter__DOT__y_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__0__KET____DOT__converter__DOT__y_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__0__KET____DOT__converter__DOT__cb_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__0__KET____DOT__converter__DOT__cb_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__0__KET____DOT__converter__DOT__cb_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__0__KET____DOT__converter__DOT__cr_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__0__KET____DOT__converter__DOT__cr_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__0__KET____DOT__converter__DOT__cr_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__1__KET____DOT__converter__DOT__y_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__1__KET____DOT__converter__DOT__y_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__1__KET____DOT__converter__DOT__y_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__1__KET____DOT__converter__DOT__cb_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__1__KET____DOT__converter__DOT__cb_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__1__KET____DOT__converter__DOT__cb_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__1__KET____DOT__converter__DOT__cr_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__1__KET____DOT__converter__DOT__cr_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__1__KET____DOT__converter__DOT__cr_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__2__KET____DOT__converter__DOT__y_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__2__KET____DOT__converter__DOT__y_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__2__KET____DOT__converter__DOT__y_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__2__KET____DOT__converter__DOT__cb_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__2__KET____DOT__converter__DOT__cb_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__2__KET____DOT__converter__DOT__cb_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__2__KET____DOT__converter__DOT__cr_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__2__KET____DOT__converter__DOT__cr_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__2__KET____DOT__converter__DOT__cr_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__3__KET____DOT__converter__DOT__y_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__3__KET____DOT__converter__DOT__y_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__3__KET____DOT__converter__DOT__y_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__3__KET____DOT__converter__DOT__cb_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__3__KET____DOT__converter__DOT__cb_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__3__KET____DOT__converter__DOT__cb_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__3__KET____DOT__converter__DOT__cr_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__3__KET____DOT__converter__DOT__cr_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__3__KET____DOT__converter__DOT__cr_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__4__KET____DOT__converter__DOT__y_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__4__KET____DOT__converter__DOT__y_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__4__KET____DOT__converter__DOT__y_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__4__KET____DOT__converter__DOT__cb_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__4__KET____DOT__converter__DOT__cb_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__4__KET____DOT__converter__DOT__cb_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__4__KET____DOT__converter__DOT__cr_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__4__KET____DOT__converter__DOT__cr_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__4__KET____DOT__converter__DOT__cr_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__5__KET____DOT__converter__DOT__y_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__5__KET____DOT__converter__DOT__y_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__5__KET____DOT__converter__DOT__y_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__5__KET____DOT__converter__DOT__cb_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__5__KET____DOT__converter__DOT__cb_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__5__KET____DOT__converter__DOT__cb_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__5__KET____DOT__converter__DOT__cr_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__5__KET____DOT__converter__DOT__cr_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__5__KET____DOT__converter__DOT__cr_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__6__KET____DOT__converter__DOT__y_r_mul__DOT__result;
    };
    struct {
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__6__KET____DOT__converter__DOT__y_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__6__KET____DOT__converter__DOT__y_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__6__KET____DOT__converter__DOT__cb_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__6__KET____DOT__converter__DOT__cb_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__6__KET____DOT__converter__DOT__cb_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__6__KET____DOT__converter__DOT__cr_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__6__KET____DOT__converter__DOT__cr_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__6__KET____DOT__converter__DOT__cr_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__7__KET____DOT__converter__DOT__y_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__7__KET____DOT__converter__DOT__y_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__7__KET____DOT__converter__DOT__y_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__7__KET____DOT__converter__DOT__cb_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__7__KET____DOT__converter__DOT__cb_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__7__KET____DOT__converter__DOT__cb_b_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__7__KET____DOT__converter__DOT__cr_r_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__7__KET____DOT__converter__DOT__cr_g_mul__DOT__result;
        IData/*23:0*/ connect__DOT__rgb2ycbcr_inst__DOT__converter_cores__BRA__7__KET____DOT__converter__DOT__cr_b_mul__DOT__result;
        IData/*31:0*/ connect__DOT__dct_y__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ connect__DOT__dct_y__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ connect__DOT__dct_y__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ connect__DOT__dct_y__DOT__unnamedblk6__DOT__j;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__s0;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__s1;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__s2;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__s3;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__d0;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__d1;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__d2;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__d3;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__e0;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__e1;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__e2;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__e3;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__b0;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__b1;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__b2;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__b3;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__b4;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__b5;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__b6;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__b7;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__t_b1;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__t_b5;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__0__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__1__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__2__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__3__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__4__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__5__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__6__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_y__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__7__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__unnamedblk6__DOT__j;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__s0;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__s1;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__s2;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__s3;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__d0;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__d1;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__d2;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__d3;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__e0;
    };
    struct {
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__e1;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__e2;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__e3;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__b0;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__b1;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__b2;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__b3;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__b4;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__b5;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__b6;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__b7;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__t_b1;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__t_b5;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__0__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__1__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__2__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__3__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__4__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__5__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__6__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__7__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__unnamedblk1__DOT__j;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__unnamedblk6__DOT__j;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__s0;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__s1;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__s2;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__s3;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__d0;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__d1;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__d2;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__d3;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__e0;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__e1;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__e2;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__e3;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__b0;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__b1;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__b2;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__b3;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__b4;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__b5;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__b6;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__b7;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__t_b1;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__t_b5;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__0__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__1__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__2__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__3__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__4__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__5__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__6__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT____Vcellout__mult_inst__BRA__7__KET____DOT__multiplier__result;
        IData/*31:0*/ connect__DOT__quant_y__DOT__j;
        IData/*31:0*/ connect__DOT__quant_y__DOT____Vcellout__GEN_MULTS__BRA__0__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_y__DOT____Vcellout__GEN_MULTS__BRA__1__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_y__DOT____Vcellout__GEN_MULTS__BRA__2__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_y__DOT____Vcellout__GEN_MULTS__BRA__3__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_y__DOT____Vcellout__GEN_MULTS__BRA__4__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_y__DOT____Vcellout__GEN_MULTS__BRA__5__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_y__DOT____Vcellout__GEN_MULTS__BRA__6__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_y__DOT____Vcellout__GEN_MULTS__BRA__7__KET____DOT__u_mul__result;
    };
    struct {
        IData/*31:0*/ connect__DOT__quant_cb__DOT__j;
        IData/*31:0*/ connect__DOT__quant_cb__DOT____Vcellout__GEN_MULTS__BRA__0__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_cb__DOT____Vcellout__GEN_MULTS__BRA__1__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_cb__DOT____Vcellout__GEN_MULTS__BRA__2__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_cb__DOT____Vcellout__GEN_MULTS__BRA__3__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_cb__DOT____Vcellout__GEN_MULTS__BRA__4__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_cb__DOT____Vcellout__GEN_MULTS__BRA__5__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_cb__DOT____Vcellout__GEN_MULTS__BRA__6__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_cb__DOT____Vcellout__GEN_MULTS__BRA__7__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_cr__DOT__j;
        IData/*31:0*/ connect__DOT__quant_cr__DOT____Vcellout__GEN_MULTS__BRA__0__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_cr__DOT____Vcellout__GEN_MULTS__BRA__1__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_cr__DOT____Vcellout__GEN_MULTS__BRA__2__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_cr__DOT____Vcellout__GEN_MULTS__BRA__3__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_cr__DOT____Vcellout__GEN_MULTS__BRA__4__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_cr__DOT____Vcellout__GEN_MULTS__BRA__5__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_cr__DOT____Vcellout__GEN_MULTS__BRA__6__KET____DOT__u_mul__result;
        IData/*31:0*/ connect__DOT__quant_cr__DOT____Vcellout__GEN_MULTS__BRA__7__KET____DOT__u_mul__result;
        IData/*31:0*/ __VactIterCount;
        QData/*47:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__mult_inst__BRA__0__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__mult_inst__BRA__1__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__mult_inst__BRA__2__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__mult_inst__BRA__3__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__mult_inst__BRA__4__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__mult_inst__BRA__5__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__mult_inst__BRA__6__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_y__DOT__u_dct__DOT__mult_inst__BRA__7__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__mult_inst__BRA__0__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__mult_inst__BRA__1__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__mult_inst__BRA__2__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__mult_inst__BRA__3__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__mult_inst__BRA__4__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__mult_inst__BRA__5__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__mult_inst__BRA__6__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_cb__DOT__u_dct__DOT__mult_inst__BRA__7__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__mult_inst__BRA__0__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__mult_inst__BRA__1__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__mult_inst__BRA__2__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__mult_inst__BRA__3__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__mult_inst__BRA__4__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__mult_inst__BRA__5__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__mult_inst__BRA__6__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__dct_cr__DOT__u_dct__DOT__mult_inst__BRA__7__KET____DOT__multiplier__DOT__p;
        QData/*47:0*/ connect__DOT__quant_y__DOT__GEN_MULTS__BRA__0__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_y__DOT__GEN_MULTS__BRA__1__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_y__DOT__GEN_MULTS__BRA__2__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_y__DOT__GEN_MULTS__BRA__3__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_y__DOT__GEN_MULTS__BRA__4__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_y__DOT__GEN_MULTS__BRA__5__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_y__DOT__GEN_MULTS__BRA__6__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_y__DOT__GEN_MULTS__BRA__7__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_cb__DOT__GEN_MULTS__BRA__0__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_cb__DOT__GEN_MULTS__BRA__1__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_cb__DOT__GEN_MULTS__BRA__2__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_cb__DOT__GEN_MULTS__BRA__3__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_cb__DOT__GEN_MULTS__BRA__4__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_cb__DOT__GEN_MULTS__BRA__5__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_cb__DOT__GEN_MULTS__BRA__6__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_cb__DOT__GEN_MULTS__BRA__7__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_cr__DOT__GEN_MULTS__BRA__0__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_cr__DOT__GEN_MULTS__BRA__1__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_cr__DOT__GEN_MULTS__BRA__2__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_cr__DOT__GEN_MULTS__BRA__3__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_cr__DOT__GEN_MULTS__BRA__4__KET____DOT__u_mul__DOT__p;
    };
    struct {
        QData/*47:0*/ connect__DOT__quant_cr__DOT__GEN_MULTS__BRA__5__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_cr__DOT__GEN_MULTS__BRA__6__KET____DOT__u_mul__DOT__p;
        QData/*47:0*/ connect__DOT__quant_cr__DOT__GEN_MULTS__BRA__7__KET____DOT__u_mul__DOT__p;
        VlUnpacked<CData/*7:0*/, 8> connect__DOT__rgb2ycbcr_inst__DOT__r_core;
        VlUnpacked<CData/*7:0*/, 8> connect__DOT__rgb2ycbcr_inst__DOT__g_core;
        VlUnpacked<CData/*7:0*/, 8> connect__DOT__rgb2ycbcr_inst__DOT__b_core;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__rgb2ycbcr_inst__DOT__y_core;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__rgb2ycbcr_inst__DOT__cb_core;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__rgb2ycbcr_inst__DOT__cr_core;
        VlUnpacked<IData/*31:0*/, 64> connect__DOT__dct_y__DOT__input_buffer;
        VlUnpacked<IData/*31:0*/, 64> connect__DOT__dct_y__DOT__output_buffer;
        VlUnpacked<IData/*31:0*/, 64> connect__DOT__dct_y__DOT__trans_buff;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_y__DOT__wdata_trans;
        VlUnpacked<CData/*5:0*/, 8> connect__DOT__dct_y__DOT__raddr_trans;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_y__DOT__rdata_trans;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_y__DOT__core_in;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_y__DOT__core_out;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_y__DOT__u_dct__DOT__y;
        VlUnpacked<QData/*47:0*/, 8> connect__DOT__dct_y__DOT__u_dct__DOT__job;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_y__DOT__u_dct__DOT__mul_y;
        VlUnpacked<IData/*31:0*/, 64> connect__DOT__dct_cb__DOT__input_buffer;
        VlUnpacked<IData/*31:0*/, 64> connect__DOT__dct_cb__DOT__output_buffer;
        VlUnpacked<IData/*31:0*/, 64> connect__DOT__dct_cb__DOT__trans_buff;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_cb__DOT__wdata_trans;
        VlUnpacked<CData/*5:0*/, 8> connect__DOT__dct_cb__DOT__raddr_trans;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_cb__DOT__rdata_trans;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_cb__DOT__core_in;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_cb__DOT__core_out;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_cb__DOT__u_dct__DOT__y;
        VlUnpacked<QData/*47:0*/, 8> connect__DOT__dct_cb__DOT__u_dct__DOT__job;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_cb__DOT__u_dct__DOT__mul_y;
        VlUnpacked<IData/*31:0*/, 64> connect__DOT__dct_cr__DOT__input_buffer;
        VlUnpacked<IData/*31:0*/, 64> connect__DOT__dct_cr__DOT__output_buffer;
        VlUnpacked<IData/*31:0*/, 64> connect__DOT__dct_cr__DOT__trans_buff;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_cr__DOT__wdata_trans;
        VlUnpacked<CData/*5:0*/, 8> connect__DOT__dct_cr__DOT__raddr_trans;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_cr__DOT__rdata_trans;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_cr__DOT__core_in;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_cr__DOT__core_out;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_cr__DOT__u_dct__DOT__y;
        VlUnpacked<QData/*47:0*/, 8> connect__DOT__dct_cr__DOT__u_dct__DOT__job;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__dct_cr__DOT__u_dct__DOT__mul_y;
        VlUnpacked<IData/*31:0*/, 64> connect__DOT__quant_y__DOT__luma_table_rom;
        VlUnpacked<IData/*31:0*/, 64> connect__DOT__quant_y__DOT__chroma_table_rom;
        VlUnpacked<SData/*15:0*/, 64> connect__DOT__quant_y__DOT__result_buffer;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__quant_y__DOT__pixel_in;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__quant_y__DOT__qtable_in;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__quant_y__DOT__mul_out;
        VlUnpacked<IData/*31:0*/, 64> connect__DOT__quant_cb__DOT__luma_table_rom;
        VlUnpacked<IData/*31:0*/, 64> connect__DOT__quant_cb__DOT__chroma_table_rom;
        VlUnpacked<SData/*15:0*/, 64> connect__DOT__quant_cb__DOT__result_buffer;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__quant_cb__DOT__pixel_in;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__quant_cb__DOT__qtable_in;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__quant_cb__DOT__mul_out;
        VlUnpacked<IData/*31:0*/, 64> connect__DOT__quant_cr__DOT__luma_table_rom;
        VlUnpacked<IData/*31:0*/, 64> connect__DOT__quant_cr__DOT__chroma_table_rom;
        VlUnpacked<SData/*15:0*/, 64> connect__DOT__quant_cr__DOT__result_buffer;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__quant_cr__DOT__pixel_in;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__quant_cr__DOT__qtable_in;
        VlUnpacked<IData/*31:0*/, 8> connect__DOT__quant_cr__DOT__mul_out;
        VlUnpacked<CData/*0:0*/, 5> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vconnect__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vconnect___024root(Vconnect__Syms* symsp, const char* v__name);
    ~Vconnect___024root();
    VL_UNCOPYABLE(Vconnect___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
